sudo: required
dist: trusty
branches:
  except:
    - gh-pages
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
before_install:
  - npm i npm@^4 -g
  - npm i yarn
install:
  - yarn install
script:
  - npm run build:release
  - bash ./deploy-docs.sh
env:
  global:
    - GH_REF: github.com/nomadreservations/virtual-scroll.git
notifications:
  email: false
